import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import UserContextProvider from "@/context/UserContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
      <html lang="en">
        <body className={`${inter.className}`}> {children}</body>
      </html>
    </UserContextProvider>
  );
}
